// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3JQgp7Q5GiI0zlC5i-Qs2W9tUvxPew5k',
    appId: '1:316147822294:android:4560e9b3f7352d56922377',
    messagingSenderId: '316147822294',
    projectId: 'repo-edc2d',
    storageBucket: 'repo-edc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFPW2aDg0gFDNr_0J4xs8SxrEO2whXW14',
    appId: '1:316147822294:ios:92f2ddc4086edf87922377',
    messagingSenderId: '316147822294',
    projectId: 'repo-edc2d',
    storageBucket: 'repo-edc2d.appspot.com',
    androidClientId: '316147822294-mb5f0n9m570ui4bj4a525u1nji32c01t.apps.googleusercontent.com',
    iosClientId: '316147822294-sdv9umq71jegdo5fi0mu3gusdet4vo1u.apps.googleusercontent.com',
    iosBundleId: 'com.app.nexishive',
  );

}